---
title: "Bab 3, Latihan Soal"
format: html
---

## Sebaran Eksponensial

Misal $X_1, X_2, \ldots, X_n$ menyebar bebas stokastik identik, $\mathrm{Eksponensial}(\theta)$. Berilah penduga kemungkinan maksimum bagi $\theta$! Apakah berbias?

Fungsi kepekatan peluang $\mathrm{Eksponensial}(\theta)$ adalah:

$$
f(x_i)=\frac{1}{\theta}e^{-x_i/\theta}
$$

Maka log-nya adalah:

$$
\begin{aligned}
\log\left[f(x_i)\right]&=\log\left[\frac{1}{\theta}e^{-x_i/\theta}\right]=\log\frac{1}{\theta}+\log e^{-x_i/\theta}\\
&= -\log\theta-\frac{x_i}{\theta}
\end{aligned}
$$

Dan log-likelihood:

$$
\begin{aligned}
l(\theta)&=\sum_{i=1}^n\log\left[f(x_i)\right]=\sum_{i=1}^n \left\{-\log\theta-\frac{x_i}{\theta}\right\}\\
&=-n\log\theta-\frac{1}{\theta}\sum_{i=1}^n x_{i}
\end{aligned}
$$

Lalu cari turunan pada $\theta$; note, turunan $\partial \log(x)/\partial x=1/x$:

$$
\begin{aligned}
\frac{\partial l(\theta)}{\partial \theta}&=-\frac{n}{\theta}+\frac{1}{\theta^2}\sum_{i=1}^n x_{i}
\end{aligned}
$$

Karena $-1/\theta=-\theta^{-1}$, sehingga turunannya adalah $\theta^{-2}$. Lalu buat nilai turunan tersebut sama dengan nol, dan cari penduga untuk $\theta$:

$$
\begin{aligned}
\frac{\partial l(\theta)}{\partial \theta}&=-\frac{n}{\theta}+\frac{1}{\theta^2}\sum_{i=1}^n x_{i}=0\\
&=\frac{1}{\theta}\left(-n+\frac{1}{\theta}\sum_{i=1}^n x_i\right)=0\\
&=\theta\cdot\frac{1}{\theta}\left(\cdots\right)=\theta\cdot0\\
&=-n+\frac{1}{\theta}\sum_{i=1}^n x_i=0\\
&=\frac{1}{\theta}\sum_{i=1}^n x_{i}=n\\
&=\frac{\sum_{i=1}^n x_i}{n}=\theta\\
&=\bar{x}
\end{aligned}
$$

Maka penduga bagi $\theta$ adalah $\bar{x}$. Coba uji turunan kedua:

$$
\begin{aligned}
\frac{\partial^2 l(\theta)}{\partial \theta^2}&=\frac{n}{\theta^2}-\frac{2}{\theta^3}\sum_{i=1}^n x_{i}&\\
&=\frac{1}{\theta^2}\left[n-\frac{2}{\theta}\sum_{i=1}^n x_i\right]& \text{substitusi }\theta \text{ dengan } \bar{x}\\
&=\frac{1}{\bar{x}^2}\left[n-\frac{2}{\frac{\sum_{i=1}^n x_i}{n}}\sum_{i=1}^n x_i\right]\\
&=\bar{x}^2\left[n-2n\right]=-n\bar{x}^2 <0
\end{aligned}
$$

Sehingga turunan kedua negatif.

Bias dari penduga tersebut juga dapat dicari, dengan mengetahui bahwa $E\left[X\right]=\theta$ untuk eksponensial:

$$
E\left[\bar{x}\right]=E\left[\frac{\sum_{i=1}^n x_i}{n}\right]=\frac{1}{n}\left[n\theta\right]=\theta
$$

Ragam dari penduga juga dapat dicari.

## Sebaran binomial

$X$ adalah satu jika suatu percobaan Bernoulli sukses dan nol jika percobaan tersebut gagal, dengan probabilitas sukses $\theta$. $X_1, X_2, \ldots, X_n$ merupakan contoh acak dari $X$, dengan n diketahui. Temukan penduga kemungkinan maksimum dan cek biasnya!

Fungsi massa peluang Bernoulli:

$$
p(x\ | \ \theta)=\theta^x(1-\theta)^{1-x}, \ x=0 \text{ atau }1
$$

Maka log dari fungsi tersebut adalah:
$$
\log\left[p(x \ | \ \theta)\right]=x\log\theta+(1-x)\log(1-\theta)
$$

Sehingga fungsi log-likelihood:

$$
\begin{aligned}
l(\theta)&=\sum_{i=1}^n\log\left[p(x_i \ | \ \theta)\right]=\sum_{i=1}^n x_i \log \theta+\left(n-\sum_{i=1}^n x_i\right)\log(1-\theta)\\
\end{aligned}
$$

Cari turunannya dan buat nol:

$$
\begin{aligned}
\frac{\partial l(\theta)}{\partial \theta}&=\frac{\sum_{i=1}^n x_i}{\theta}-\frac{n-\sum_{i=1}^n x_i}{1-\theta}=0\\
&=\frac{\sum_{i=1}^n x_i}{\theta}=\frac{n-\sum_{i=1}^n x_i}{1-\theta}\\
&=\sum_{i=1}^n x_i-\theta\sum_{i=1}^n x_i=\theta n-\theta\sum_{i=1}^n x_i\\
&=\sum_{i=1}^n x_i-\theta\sum_{i=1}^n x_i+\theta\sum_{i=1}^n x_i=\theta n-\theta\sum_{i=1}^n x_i+\theta\sum_{i=1}^n x_i\\
&=\sum_{i=1}^n x_i=\theta n\\
&=\frac{\sum_{i=1}^n x_i}{n}=\theta
\end{aligned}
$$

Atau, proporsi kejadian sukses dari semua kejadian. Karena $E(x_i)=p$, maka jelas penduga tersebut takbias, karena $\sum_{i=1}^n p=np$; jika dibagi n maka ketakbiasan terbukti.

Cek juga turunan kedua:

$$
\begin{aligned}
\frac{\partial^2 l(\theta)}{\partial \theta^2}&=-\frac{\sum_{i=1}^n x_i}{\theta^2}-\frac{n-\sum_{i=1}^n x_i}{(1-\theta)^2}<0
\end{aligned}
$$

Karena $X$ hanya memiliki nilai 1 atau 0, term $sum_{i=1}^n x_i$ pasti positif dan lebih kecil atau sama dengan $n$. Oleh karena itu jelas bahwa $-\sum_{i=1}^n x_i$ pasti negatif. Lalu $n-\sum_{i=1}^n x_i$ tidak mungkin negatif, sehingga minusnya tidak mungkin positif.

## Sebaran Normal

$X_1, X_2, \ldots, X_n$ merupakan contoh acak dari $X\sim N(\mu,\sigma^2)$. Cari penduga kemungkinan maksimum untuk vektor $\theta=(\mu, \sigma^2)$:

Log dari fungsi kepekatan peluang:
$$
\begin{aligned}
\log\left[f(x_i\ | \ \theta)\right]&=\log\left[\frac{1}{\sigma\sqrt{2\pi}}\exp\left\{-\frac{1}{2}\left(\frac{x_i-\mu}{\sigma}\right)^2\right\}\right]\\
&=\log\frac{1}{\sigma}+\log\frac{1}{2\pi}-\frac{1}{2}\left(\frac{x_i-\mu}{\sigma}\right)^2\\
&=-\log\sigma-\log2\pi-\frac{1}{2}\left(\frac{x_i-\mu}{\sigma}\right)^2
\end{aligned}
$$

Lalu cari fungsi log-likelihood:

$$
\begin{aligned}
l(\theta)&=\sum_{i=1}^n\log\left[f(x_i \ | \ \theta)\right]\\
&=-n\log\sigma-n\log2\pi-\frac{1}{2}\sum_{i=1}^n\left(\frac{x_i-\mu}{\sigma}\right)^2\\
\end{aligned}
$$

Lalu turunkan:

$$
\begin{aligned}
\frac{\partial l(\mu, \sigma)}{\partial \mu}&=-\frac{1}{2}\cdot2\sum_{i=1}^n\left[\frac{\partial}{\partial \mu}\left(\frac{x_i-\mu}{\sigma}\right)\right]\\
&=\frac{1}{\sigma}\sum_{i=1}^n\left(\frac{x_i-\mu}{\sigma}\right)=\frac{1}{\sigma^2}\sum_{i=1}^n (x_i-\mu)\\
\frac{\partial l(\mu, \sigma)}{\partial \sigma}
&=-\frac{n}{\sigma}-\frac{1}{2}\sum_{i=1}^n\left(x_i-\mu\right)^2\frac{\partial }{\partial \sigma}\left(\sigma\right)^{-2}\\
&=-\frac{n}{\sigma}+\frac{1}{\sigma^3}\sum_{i=1}^n (x_i-\mu)^2
\end{aligned}
$$

Untuk membuat persamaan pertama nol, haruslah $\sum_{i=1}^n (x_i-\mu)$ nol. Maka haruslah $n\bar{X}-n\mu=0$, dan $\bar{X}=\mu$ menjadi penduga nilai harapan.

Jika penduga tersebut dimasukkan ke persamaan kedua, maka dimiliki:

$$
\begin{aligned}
0&=-\frac{n}{\sigma}+\frac{1}{\sigma^3}\sum_{i=1}^n (x_i-\bar{x})^2\\
\sigma^3\cdot\frac{n}{\sigma}&=\sigma^3\cdot\frac{1}{\sigma^3}\sum_{i=1}^n (x_i-\bar{x})^2\\
\sigma^2n&=\sum_{i=1}^n (x_i-\bar{x})^2\\
\sigma^2&=\frac{\sum_{i=1}^n (x_i-\bar{x})^2}{n}
\end{aligned}
$$

Sehingga ditemukan penduga kemungkinan maksimum $\sigma^2$.

## Sebaran Seragam (0,\theta)

Untuk menghitung penduga kemungkinan maksimum sebaran seragam, perlu pengetahuan mengenai konsep *fungsi indikator*. $I(a,b)$ adalah 1 jika $a\leq b$ dan 0 jika $a>b$. Oleh karena sebaran $Seragam(0,\theta)$ memiliki fungsi kepekatan peluang:

$$
\begin{aligned}
f(x \ | \ \theta)&=\begin{cases}
\frac{1}{\theta}, &0\leq x_i\leq\theta \\
0, & lainnya
\end{cases}
\\&=\frac{1}{\theta}I(x_i,\theta)
\end{aligned}
$$

Karena jika $x_i$ di luar selang tersebut,fungsi indikator akan nol. Karena sudah diketahui batas bawah sebaran adalah 0, semua nilai di contoh acak pastilah lebih dari nol. Maka fungsi likelihoodnya adalah:

$$
L(\theta)=\frac{1}{\theta^n}\prod_{i=1}^n I(x_i,\theta)
$$

Note nilai yang mungkin untuk fungsi indikator adalah $1$ jika semua $x_i\leq\theta$ dan $0$ jika setidaknya satu $x_i>\theta$. Namun $max(x_i)\geq x_i$ sehingga jika $max(x_i)\leq \theta$ pastilah semua $x_i\leq\theta$. Sehingga fungsi likelihood ditulis:

$$
L(\theta)=\frac{1}{\theta^n}\prod_{i=1}^n I(max\{x_i\},\theta)
$$

Tentu, kita ingin $\theta$ sekecil mungkin agar pembagi sekecil mungkin dan fungsi likelihood sebesar mungkin, tetapi dengan syarat $max\{x_i\}\leq\theta$. Oleh karena itu penduga kemungkinan maksimum adalah $max\{x_i\}$