---
title: "Bab 3 - Pendugaan Kemungkinan Maksimum"
editor: visual
author: "Ayunda Afiani Rosita, Muhammad Ammar Sahab"
format:
  html:
    self-contained: true
    theme: simplex
---

## Fungsi likelihood

Untuk mengilustrasikan konsep fungsi likelihood, bayangkan kita hendak menentukan jumlah lampu rusak di kotak yang berisi 5 lampu. Anda mengambil 2 lampu sebagai sampel, lalu menemukan bahwa dua-duanya rusak. Probabilitas $y$ jumlah rusak terambil dari sampel berukuran $n$ dapat dimodelkan dengan sebaran hipergeometris:

$$
p(y)=\frac{{r\choose y}{{N-r}\choose{n-y}}}{N\choose n}
$$

Di mana $N$ adalah jumlah populasi, $r$ jumlah lampu rusak sebenarnya. Maka probabilitas tersebut memiliki bentuk:

$$
p\bigl(y=2 \ | \ r=2\bigr)=\frac{{r\choose 2}{{5-r}\choose{0}}}{5\choose 2}
$$

Tentu $r\geq 2$. Tidak mungkin lampu rusak kurang dari 2 kalau sudah terambil dua lampu rusak, sehingga ada beberapa kemungkinan:

$$
\begin{aligned}
p\bigl(y=2 \ | \ r=2\bigr)&=\frac{{2\choose 2}{{3}\choose{0}}}{5\choose 2}=\frac{1}{5\choose 2}\\
p\bigl(y=2 \ | \ r=3\bigr)&=\frac{{3\choose 2}{{2}\choose{0}}}{5\choose 2}=\frac{3}{5\choose 2}\\
p\bigl(y=2 \ | \ r=4\bigr)&=\frac{{4\choose 2}{{1}\choose{0}}}{5\choose 2}=\frac{6}{5\choose 2}\\
p\bigl(y=2 \ | \ r=5\bigr)&=\frac{{5\choose 2}{{0}\choose{0}}}{5\choose 2}=1\\
&\text{Note: peluang maksimum 1}
\end{aligned}
$$

Berapa dugaan $r$ yang akan kita pilih? Dugaan yang cukup masuk akal adalah $r=5$, atau semua lampu rusak. Dugaan ini memaksimumkan probabilitas mendapat 2 lampu rusak di sampel kita.

Pencarian penduga parameter yang memaksimumkan probabilitas ditemukan sampel yang didapat dari proses pengumpulan data adalah inti dari metode kemungkinan maksimum.

Sebelum melihat fungsi likelihood, perhatikan fungsi massa $p(y)$ atau kepekatan peluang $f(y)$ terlebih dahulu. Sebenarnya fungsi ini tidak hanya bergantung pada nilai y yang ditemukan, tetapi parameter-parameter juga. Misal fungsi massa peluang binomial:

$$
p(y \ | \ n,\ p)= {n\choose y} p^y(1-p)^{n-y}
$$

Terlihat bahwa probabilitas juga bergantung pada nilai $n$ dan $p$ yang dipilih; oleh karena itu, fungsi kepekatan peluang dapat dinotasikan dengan $f(Y=y \ | \ \theta)$ - notasi peluang bersyarat - yang berarti peluang peubah acak $Y$ memiliki nilai $y$ jika parameter $\theta$ memiliki nilai tertentu. Oleh karena itu, nilai parameter $\theta$ dan parameter lainnya, jika tak diketahui, dapat dipilih untuk memaksimumkan probabilitas.

Namun, dalam mengambil data dari sampel, tentu tidak hanya ada observasi $Y$. Ada observasi $Y_1, Y_2, Y_3, \ldots, Y_n$ yang dianggap memiliki sebaran identik dan saling bebas. Oleh karena itu, perlu menghitung peluang bersama muncul sampel tersebut. Tentu, jika peubah acak $A$ dan $B$ saling bebas, diketahui bahwa $P(A,B)=P(A)\cdot P(B)$. Maka:

$$
f(y_1,y_2,\ldots,y_n\ | \ \theta=\hat{\theta})= \prod_{i=1}^n f(y_{i} \ | \theta= \ \hat{\theta})
$$

Fungsi tersebut disebut fungsi likelihood. Karena sampel berisi observasi $Y_1, Y_2, \ldots, Y_n$ dianggap sudah diketahui, maka input fungsi adalah parameter. Dalam kata lain:

$$
L(\theta) = L(\theta \ | \ y_{1}, y_{2}, \ldots, y_n)=\prod_{i=1}^n f(x_i \ | \ \theta)
$$

## Pemaksimuman Likelihood

Untuk memaksimumkan likelihood:

$$
\mathrm{argmax} \ L(\theta)
$$

Dari Kalkulus, pemaksimuman fungsi dilakukan saat:

$$
\begin{aligned}
\frac{\partial L}{\partial\theta}&=0\\
\frac{\partial^2 L}{\partial\theta^2}&<0
\end{aligned}
$$

Ini berarti nilai fungsi tidak naik atau turun di tempat tersebut. Lalu, sebelumnya perubahan kenaikan/penurunan negatif - jika fungsi tidak naik dan tidak turun, ini berarti sebelumnya fungsi naik, tetapi lama kelamaan melandai sehingga jadi maksimum.

Tentu, biasanya lebih mudah menghitung turunan dari operasi penambahan daripada perkalian. Oleh karena itu, dibuat fungsi bernama log-likelihood. Karena fungsi log selalu naik, maka maksimum dari log-likelihood sama dengan maksimum dari likelihood:

$$
\begin{aligned}
l(\theta)&=\log[L(\theta)]=\log\left[\prod_{i=1}^n f(x_i \ | \ \theta)\right]\\
&=\sum_{i=1}^n \log \left[f(x_i \ | \ \theta)\right]
\end{aligned}
$$

Oleh karena itu, langkah-langkah menetukan penduga kemumgkinan maksimum adalah:

1.  Cari fungsi kepekatan/massa peluang dari sebaran yang parameternya hendak diduga.
2.  Cari log dari fungsi tersebut.
3.  Cari jumlah dari 1 ke n log fungsi kepekatan/massa peluang. Itulah fungsi log-likelihood.
4.  Cari turunan pertama dari log-likelihood.
5.  Cari $\hat{\theta}$, penduga yang membuat turunan pertama tersebut nol.
6.  Pastikan turunan kedua dari log-likelihood di titik tersebut juga nol.

Atau, dapat dicari fungsi likelihood terlebih dahulu:

1.  Cari fungsi kepekatan/massa peluang bersama dengan mengalikan fungsi kepekatan/massa peluang dari 1 ke n
2.  Cari log dari fungsi tersebut.

Lalu lanjutkan langkah 4-6.

## Contoh

### Sebaran Eksponensial

Misal $X_1, X_2, \ldots, X_n$ menyebar bebas stokastik identik, $\mathrm{Eksponensial}(\theta)$. Berilah penduga kemungkinan maksimum bagi $\theta$! Apakah berbias?

Fungsi kepekatan peluang $\mathrm{Eksponensial}(\theta)$ adalah:

$$
f(x_i)=\frac{1}{\theta}e^{-x_i/\theta}
$$

Maka log-nya adalah:

$$
\begin{aligned}
\log\left[f(x_i)\right]&=\log\left[\frac{1}{\theta}e^{-x_i/\theta}\right]=\log\frac{1}{\theta}+\log e^{-x_i/\theta}\\
&= -\log\theta-\frac{x_i}{\theta}
\end{aligned}
$$

Dan log-likelihood:

$$
\begin{aligned}
l(\theta)&=\sum_{i=1}^n\log\left[f(x_i)\right]=\sum_{i=1}^n \left\{-\log\theta-\frac{x_i}{\theta}\right\}\\
&=-n\log\theta-\frac{1}{\theta}\sum_{i=1}^n x_{i}
\end{aligned}
$$

Lalu cari turunan pada $\theta$; note, turunan $\partial \log(x)/\partial x=1/x$:

$$
\begin{aligned}
\frac{\partial l(\theta)}{\partial \theta}&=-\frac{n}{\theta}+\frac{1}{\theta^2}\sum_{i=1}^n x_{i}
\end{aligned}
$$

Karena $-1/\theta=-\theta^{-1}$, sehingga turunannya adalah $\theta^{-2}$. Lalu buat nilai turunan tersebut sama dengan nol, dan cari penduga untuk $\theta$:

$$
\begin{aligned}
\frac{\partial l(\theta)}{\partial \theta}&=-\frac{n}{\theta}+\frac{1}{\theta^2}\sum_{i=1}^n x_{i}=0\\
&=\frac{1}{\theta}\left(-n+\frac{1}{\theta}\sum_{i=1}^n x_i\right)=0\\
&=\theta\cdot\frac{1}{\theta}\left(\cdots\right)=\theta\cdot0\\
&=-n+\frac{1}{\theta}\sum_{i=1}^n x_i=0\\
&=\frac{1}{\theta}\sum_{i=1}^n x_{i}=n\\
&=\frac{\sum_{i=1}^n x_i}{n}=\theta\\
&=\bar{x}
\end{aligned}
$$

Maka penduga bagi $\theta$ adalah $\bar{x}$. Coba uji turunan kedua:

$$
\begin{aligned}
\frac{\partial^2 l(\theta)}{\partial \theta^2}&=\frac{n}{\theta^2}-\frac{2}{\theta^3}\sum_{i=1}^n x_{i}&\\
&=\frac{1}{\theta^2}\left[n-\frac{2}{\theta}\sum_{i=1}^n x_i\right]& \text{substitusi }\theta \text{ dengan } \bar{x}\\
&=\frac{1}{\bar{x}^2}\left[n-\frac{2}{\frac{\sum_{i=1}^n x_i}{n}}\sum_{i=1}^n x_i\right]\\
&=\bar{x}^2\left[n-2n\right]=-n\bar{x}^2 <0
\end{aligned}
$$

Sehingga turunan kedua negatif.

Bias dari penduga tersebut juga dapat dicari, dengan mengetahui bahwa $E\left[X\right]=\theta$ untuk eksponensial:

$$
E\left[\bar{x}\right]=E\left[\frac{\sum_{i=1}^n x_i}{n}\right]=\frac{1}{n}\left[n\theta\right]=\theta
$$

Ragam dari penduga juga dapat dicari.

### Sebaran binomial

$X$ adalah satu jika suatu percobaan Bernoulli sukses dan nol jika percobaan tersebut gagal, dengan probabilitas sukses $\theta$. $X_1, X_2, \ldots, X_n$ merupakan contoh acak dari $X$, dengan n diketahui. Temukan penduga kemungkinan maksimum dan cek biasnya!

Fungsi massa peluang Bernoulli:

$$
p(x\ | \ \theta)=\theta^x(1-\theta)^{1-x}, \ x=0 \text{ atau }1
$$

Maka log dari fungsi tersebut adalah:
$$
\log\left[p(x \ | \ \theta)\right]=x\log\theta+(1-x)\log(1-\theta)
$$

Sehingga fungsi log-likelihood:

$$
\begin{aligned}
l(\theta)&=\sum_{i=1}^n\log\left[p(x_i \ | \ \theta)\right]=\sum_{i=1}^n x_i \log \theta+\left(n-\sum_{i=1}^n x_i\right)\log(1-\theta)\\
\end{aligned}
$$

Cari turunannya dan buat nol:

$$
\begin{aligned}
\frac{\partial l(\theta)}{\partial \theta}&=\frac{\sum_{i=1}^n x_i}{\theta}-\frac{n-\sum_{i=1}^n x_i}{1-\theta}=0\\
&=\frac{\sum_{i=1}^n x_i}{\theta}=\frac{n-\sum_{i=1}^n x_i}{1-\theta}\\
&=\sum_{i=1}^n x_i-\theta\sum_{i=1}^n x_i=\theta n-\theta\sum_{i=1}^n x_i\\
&=\sum_{i=1}^n x_i-\theta\sum_{i=1}^n x_i+\theta\sum_{i=1}^n x_i=\theta n-\theta\sum_{i=1}^n x_i+\theta\sum_{i=1}^n x_i\\
&=\sum_{i=1}^n x_i=\theta n\\
&=\frac{\sum_{i=1}^n x_i}{n}=\theta
\end{aligned}
$$

Atau, proporsi kejadian sukses dari semua kejadian. Karena $E(x_i)=p$, maka jelas penduga tersebut takbias, karena $\sum_{i=1}^n p=np$; jika dibagi n maka ketakbiasan terbukti.

Cek juga turunan kedua:

$$
\begin{aligned}
\frac{\partial^2 l(\theta)}{\partial \theta^2}&=-\frac{\sum_{i=1}^n x_i}{\theta^2}-\frac{n-\sum_{i=1}^n x_i}{(1-\theta)^2}<0
\end{aligned}
$$

Karena $X$ hanya memiliki nilai 1 atau 0, term $sum_{i=1}^n x_i$ pasti positif dan lebih kecil atau sama dengan $n$. Oleh karena itu jelas bahwa $-\sum_{i=1}^n x_i$ pasti negatif. Lalu $n-\sum_{i=1}^n x_i$ tidak mungkin negatif, sehingga minusnya tidak mungkin positif.

### Sebaran normal

$X_1, X_2, \ldots, X_n$ merupakan contoh acak dari $X\sim N(\mu,\sigma^2)$. Cari penduga kemungkinan maksimum untuk vektor $\theta=(\mu, \sigma^2)$:

Log dari fungsi kepekatan peluang:
$$
\begin{aligned}
\log\left[f(x_i\ | \ \theta)\right]&=\log\left[\frac{1}{\sigma\sqrt{2\pi}}\exp\left\{-\frac{1}{2}\left(\frac{x_i-\mu}{\sigma}\right)^2\right\}\right]\\
&=\log\frac{1}{\sigma}+\log\frac{1}{2\pi}-\frac{1}{2}\left(\frac{x_i-\mu}{\sigma}\right)^2\\
&=-\log\sigma-\log2\pi-\frac{1}{2}\left(\frac{x_i-\mu}{\sigma}\right)^2
\end{aligned}
$$

Lalu cari fungsi log-likelihood:

$$
\begin{aligned}
l(\theta)&=\sum_{i=1}^n\log\left[f(x_i \ | \ \theta)\right]\\
&=-n\log\sigma-n\log2\pi-\frac{1}{2}\sum_{i=1}^n\left(\frac{x_i-\mu}{\sigma}\right)^2\\
\end{aligned}
$$

Lalu turunkan:

$$
\begin{aligned}
\frac{\partial l(\mu, \sigma)}{\partial \mu}&=-\frac{1}{2}\cdot2\sum_{i=1}^n\left[\frac{\partial}{\partial \mu}\left(\frac{x_i-\mu}{\sigma}\right)\right]\\
&=\frac{1}{\sigma}\sum_{i=1}^n\left(\frac{x_i-\mu}{\sigma}\right)=\frac{1}{\sigma^2}\sum_{i=1}^n (x_i-\mu)\\
\frac{\partial l(\mu, \sigma)}{\partial \sigma}
&=-\frac{n}{\sigma}-\frac{1}{2}\sum_{i=1}^n\left(x_i-\mu\right)^2\frac{\partial }{\partial \sigma}\left(\sigma\right)^{-2}\\
&=-\frac{n}{\sigma}+\frac{1}{\sigma^3}\sum_{i=1}^n (x_i-\mu)^2
\end{aligned}
$$

Untuk membuat persamaan pertama nol, haruslah $\sum_{i=1}^n (x_i-\mu)$ nol. Maka haruslah $n\bar{X}-n\mu=0$, dan $\bar{X}=\mu$ menjadi penduga nilai harapan.

Jika penduga tersebut dimasukkan ke persamaan kedua, maka dimiliki:

$$
\begin{aligned}
0&=-\frac{n}{\sigma}+\frac{1}{\sigma^3}\sum_{i=1}^n (x_i-\bar{x})^2\\
\sigma^3\cdot\frac{n}{\sigma}&=\sigma^3\cdot\frac{1}{\sigma^3}\sum_{i=1}^n (x_i-\bar{x})^2\\
\sigma^2n&=\sum_{i=1}^n (x_i-\bar{x})^2\\
\sigma^2&=\frac{\sum_{i=1}^n (x_i-\bar{x})^2}{n}
\end{aligned}
$$

Sehingga penduga kemungkinan maksimum $\sigma^2$ dijelaskan di atas.

### Sebaran Seragam (0,\theta)

Untuk menghitung penduga kemungkinan maksimum sebaran seragam, perlu pengetahuan mengenai konsep *fungsi indikator*. $I(a,b)$ adalah 1 jika $a\leq b$ dan 0 jika $a>b$. Oleh karena sebaran $Seragam(0,\theta)$ memiliki fungsi kepekatan peluang:

$$
\begin{aligned}
f(x \ | \ \theta)&=\begin{cases}
\frac{1}{\theta}, &0\leq x_i\leq\theta \\
0, & lainnya
\end{cases}
\\&=\frac{1}{\theta}I(x_i,\theta)
\end{aligned}
$$

Karena jika $x_i$ di luar selang tersebut,fungsi indikator akan nol. Karena sudah diketahui batas bawah sebaran adalah 0, semua nilai di contoh acak pastilah lebih dari nol. Maka fungsi likelihoodnya adalah:

$$
L(\theta)=\frac{1}{\theta^n}\prod_{i=1}^n I(x_i,\theta)
$$

Note nilai yang mungkin untuk fungsi indikator adalah $1$ jika semua $x_i\leq\theta$ dan $0$ jika setidaknya satu $x_i>\theta$. Namun $max(x_i)\geq x_i$ sehingga jika $max(x_i)\leq \theta$ pastilah semua $x_i\leq\theta$. Sehingga fungsi likelihood ditulis:

$$
L(\theta)=\frac{1}{\theta^n}\prod_{i=1}^n I(max\{x_i\},\theta)
$$

Tentu, kita ingin $\theta$ sekecil mungkin agar pembagi sekecil mungkin dan fungsi likelihood sebesar mungkin, tetapi dengan syarat $max\{x_i\}\leq\theta$. Oleh karena itu penduga kemungkinan maksimum adalah $max\{x_i\}$